# Generated by Django 5.1 on 2026-09-14 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('rubro', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('precio', models.IntegerField()),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('agotado', 'Agotada')], default='disponible', max_length=20)),
            ],
        ),
    ]
